apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: supabase-pg
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
