apiVersion: v1
kind: Secret
metadata:
  name: sb-realtime-secret
  namespace: supabase-pg
  labels:
    app: postgres
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtZGItbGI=
  DB_NAME: cG9zdGdyZXM=
  DB_PASSWORD: eW91ci1zdXBlci1zZWNyZXQtYW5kLWxvbmctcG9zdGdyZXMtcGFzc3dvcmQ=
  DB_PORT: NTQzMg==
  DB_USER: cG9zdGdyZXM=
  JWT_SECRET: IzByQG5nZVNjQHBlIzo6eW91ci1zdXBlci1zZWNyZXQtand0LXRva2VuLXdpdGgtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25n
  PORT: NDAwMA==
  SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-realtime-config
  namespace: supabase-pg
  labels:
    app: postgres
data:
  DB_SSL: "false"
  REPLICATION_MODE: RLS
  REPLICATION_POLL_INTERVAL: "100"
  SECURE_CHANNELS: "true"
  TEMPORARY_SLOT: "true"
  SLOT_NAME: supabase_realtime_rls
  DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
  DB_ENC_KEY: supabaserealtime
  FLY_ALLOC_ID: fly123
  FLY_APP_NAME: realtime
  ERL_AFLAGS: -proto_dist inet_tcp
  ENABLE_TAILSCALE: "false"
  DNS_NODES: "''"
