apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: realtime
  name: realtime
  namespace: supabase-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: realtime
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: realtime
    spec:
      containers:
        - args:
            - bash
            - -c
            - ./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate && ./prod/rel/realtime/bin/realtime start
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: DB_PORT
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: DB_SSL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: DB_USER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: PORT
            - name: REPLICATION_MODE
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: REPLICATION_MODE
            - name: REPLICATION_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: REPLICATION_POLL_INTERVAL
            - name: SECURE_CHANNELS
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: SECURE_CHANNELS
            - name: SLOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: SLOT_NAME
            - name: TEMPORARY_SLOT
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: TEMPORARY_SLOT
            - name: DB_AFTER_CONNECT_QUERY
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: DB_AFTER_CONNECT_QUERY
            - name: DB_ENC_KEY
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: DB_ENC_KEY
            - name: FLY_ALLOC_ID
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: FLY_ALLOC_ID
            - name: FLY_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: FLY_APP_NAME
            - name: ERL_AFLAGS
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: ERL_AFLAGS
            - name: ENABLE_TAILSCALE
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: ENABLE_TAILSCALE
            - name: DNS_NODES
              valueFrom:
                configMapKeyRef:
                  name: sb-realtime-config
                  key: DNS_NODES
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: sb-realtime-secret
                  key: SECRET_KEY_BASE
          image: supabase/realtime:v0.25.1
          name: supabase-realtime
          resources: {}
      restartPolicy: Always
status: {}
