apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:771153997691:certificate/7cd38249-4159-4fe6-959b-8afc9314e7b6"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-FS-1-2-2019-08"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    io.kompose.service: kong
  name: kong
  namespace: supabase-pg
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: https
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    io.kompose.service: kong
