apiVersion: v1
kind: Secret
metadata:
  namespace: supabase-pg
  name: google-oauth-client
data:
  clientId: MTA4NDEyNDIxMjY5MS1sYjRqb3B0OWlqMXBvb2JrdGZhM2M2bWNhN2I0b2YyNS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  clientSecret: R09DU1BYLWtrRGMtT2lWaW1rQUZrUy15WGFfSHVEUFVGZG0=