#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: postgres-config
#  namespace: supabase-pg
#  labels:
#    app: postgres
#data:
#  KEY: value
#
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: supabase-pg
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: eW91ci1zdXBlci1zZWNyZXQtYW5kLWxvbmctcG9zdGdyZXMtcGFzc3dvcmQ=
