apiVersion: v1
kind: Secret
metadata:
  name: sb-rest-secret
  namespace: supabase-pg
  labels:
    app: postgres
type: Opaque
data:
  PGRST_DB_SCHEMAS: cHVibGljLHN0b3JhZ2UsZ3JhcGhxbF9wdWJsaWM=
  PGRST_DB_URI: cG9zdGdyZXM6Ly9wb3N0Z3Jlczp5b3VyLXN1cGVyLXNlY3JldC1hbmQtbG9uZy1wb3N0Z3Jlcy1wYXNzd29yZEBwb3N0Z3Jlcy1kYi1sYi5zdXBhYmFzZS1wZy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVz
  PGRST_JWT_SECRET: IzByQG5nZVNjQHBlIzo6eW91ci1zdXBlci1zZWNyZXQtand0LXRva2VuLXdpdGgtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-rest-config
  namespace: supabase-pg
  labels:
    app: postgres
data:
  PGRST_DB_ANON_ROLE: anon
  PGRST_DB_USE_LEGACY_GUCS: "false"
