apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rest
  name: rest
  namespace: supabase-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rest
    spec:
      containers:
        - env:
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  name: sb-rest-config
                  key: PGRST_DB_ANON_ROLE
            - name: PGRST_DB_SCHEMAS
              valueFrom:
                secretKeyRef:
                  name: sb-rest-secret
                  key: PGRST_DB_SCHEMAS
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: sb-rest-secret
                  key: PGRST_DB_URI
            - name: PGRST_DB_USE_LEGACY_GUCS
              valueFrom:
                configMapKeyRef:
                  name: sb-rest-config
                  key: PGRST_DB_USE_LEGACY_GUCS
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sb-rest-secret
                  key: PGRST_JWT_SECRET
          image: postgrest/postgrest:v10.1.2
          name: supabase-rest
          resources: {}
      restartPolicy: Always
status: {}
